[workspace]

members = [
	"qsspodcasts",
	"rss_management",
	"fs_utils",
	"business_core",
	"podcast_management",
	"podcast_download",
	"podcast_player",
	"path_providing",
	"frontend",
	"abstract_frontend",
	"str_to_lines",
	"data_transport",
	"autocomplete_server",
]
