[package]
name = "podcast_management"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = "2.0.0"
sha-1 = "0.10.0"
hex = "0.4.3"
chrono = "0.4"
html2text = "0.4.3"
