[package]
name = "qsspodcasts"
version = "0.1.0"
authors = ["Quessours"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
business_core= { "path" = "../business_core" }
clap = { version = "3.0", features = ["derive"] }