[package]
name = "qsspodcasts"
version = "0.1.0"
authors = ["Quessours"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.21"
business_core = { path = "../business_core" }
command_management = { path = "../command_management" }
clap = { version = "3.0", features = ["derive"] }
tokio = { version = "1.17.0", features = ["full"] }
