[package]
name = "rss_management"
version = "0.1.0"
authors = ["Maxime Mikotajewski <mmikotajewski@witekio.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = "1.9.0"
log = "0.4.11"